version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: always
    depends_on:
      - php
      - db-mysql
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - net

  php:
    container_name: php
    build:
      context: .
      dockerfile: php/Dockerfile
    volumes:
      - ./app:/var/www
      - ./php/.bash_profile:/root/.bash_profile
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      - net

  db-mysql:
    container_name: db-mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - net

networks:
  net:
    driver: bridge